---
- name: create a mysql user for DB
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks: 
  - name: Create Application Database
  mysql_db:
    name: "{{ wordpress }}"
    state: present

  - name: Create Application DB User 
  mysql_user:
    name: "{{ dbadmin }}"
    password: "{{ redhat }}"
    priv: "*.*:ALL"
    host: '%'
    state: present
   

# - name: iptables stop
#     service: name=iptables state=disabled
# - name: selinux disabled
#     service: name=selinux  state=disabled


